POST http://localhost:7071/api/TriggerBookVacation HTTP/1.1
content-type: application/json

{
	"CityName" : "Singapore",
	"HotelName" : "Hyatt",
	"AirlinesName" : "AirAsia"
}
###

GET http://localhost:7071/runtime/webhooks/durabletask/instances/e0989459165c4dbfa66948087b6b6c72?taskHub=TestHubName&connection=Storage&code=UdxCrIIigcY3n9epHQ0LXYfE1BrlTg9MpaKzAxBSxcEkZPkZKwe7/A==

###

POST https://bdotnet-demo-func5b306a0c.azurewebsites.net/api/TriggerBookVacation Http/1.1
content-type: application/json

{
	"CityName" : "Singapore",
	"HotelName" : "Hyatt",
	"AirlinesName" : "AirAsia"
}

###
GET https://bdotnet-demo-func5b306a0c.azurewebsites.net/runtime/webhooks/durabletask/instances/ba069c4d16624e16b98b438751431b51?taskHub=bdotnetdemofunc5b306a0c&connection=Storage&code=4KEodnzCsEx6st96fWuoaU4oGCYvLC2B6vuxTEf8w2N/Ull5sdmatg==
